# Generated by Django 2.2.4 on 2019-08-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('creditpoints', models.IntegerField(default=6)),
                ('value', models.DecimalField(decimal_places=1, default=1.0, max_digits=2)),
                ('weighted', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gradebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
